<a href="https://colab.research.google.com/github/K12TK013A1N/ML-30/blob/main/day5_pandas_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

#Tutorial-1

In [ ]:
pd.DataFrame({'Yes': [50,21], 'No': [131,2]})

   Yes   No
0   50  131
1   21    2

In [ ]:
pd.DataFrame({'Bob': [8,7], 'Alice': [9,10]}, index=['Product A', 'Product B'])

           Bob  Alice
Product A    8      9
Product B    7     10

In [ ]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
california_housing = pd.read_csv("./sample_data/california_housing_test.csv")

In [ ]:
california_housing.shape

(3000, 9)

In [ ]:
california_housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
california_housing.to_csv('new_california.csv')

#Tutorial-2

In [ ]:
california_housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
california_housing['total_bedrooms']

0        661.0
1        310.0
2        507.0
3         15.0
4        244.0
         ...
2995     642.0
2996    1082.0
2997     201.0
2998      14.0
2999     263.0
Name: total_bedrooms, Length: 3000, dtype: float64

In [ ]:
california_housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [ ]:
california_housing.iloc[1:3,0]

1   -118.30
2   -117.81
Name: longitude, dtype: float64

In [ ]:
california_housing.loc[1:3,['longitude']]

   longitude
1    -118.30
2    -117.81
3    -118.36

In [ ]:
california_housing.set_index('longitude')
california_housing.loc[1:3]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0

In [ ]:
california_housing.loc[california_housing['longitude']==-118.30]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1,-118.3,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
31,-118.3,33.91,34.0,1617.0,493.0,1530.0,500.0,2.6182,172600.0
100,-118.3,34.02,49.0,2120.0,483.0,1522.0,416.0,1.8500,116800.0
211,-118.3,33.81,17.0,5544.0,1068.0,3008.0,1038.0,5.3220,282700.0
343,-118.3,33.97,46.0,1425.0,317.0,1140.0,304.0,3.3750,98500.0
367,-118.3,33.74,20.0,2625.0,673.0,1184.0,606.0,3.9167,285200.0
373,-118.3,33.73,42.0,1731.0,435.0,866.0,403.0,2.7451,255400.0
455,-118.3,33.97,42.0,944.0,200.0,567.0,190.0,2.6311,124100.0
524,-118.3,34.05,51.0,1005.0,314.0,1227.0,306.0,2.4297,162500.0
542,-118.3,33.88,29.0,850.0,229.0,563.0,204.0,3.7375,247700.0
803,-118.3,34.25,44.0,1442.0,285.0,859.0,292.0,4.5833,197300.0
982,-118.3,34.26,37.0,2824.0,633.0,1619.0,573.0,3.5568,184500.0
999,-118.3,34.10,29.0,3403.0,1367.0,3432.0,1174.0,1.7083,166700.0
1109,-118.3,34.19,52.0,1704.0,277.0,746.0,262.0,4.7986,326100.0
1239,-118.3,34.01,52.0,1444.0,343.0,1154.0,334.0,2.0625,134400.0
1659,-118.3,34.02,27.0,2190.0,626.0,1768.0,528.0,1.2446,103800.0
1938,-118.3,34.01,52.0,1908.0,428.0,1271.0,394.0,2.5885,136200.0
1967,-118.3,33.75,23.0,1957.0,517.0,1454.0,526.0,3.5056,203100.0
2208,-118.3,33.94,36.0,2041.0,531.0,1390.0,464.0,2.0114,99300.0
2363,-118.3,33.87,31.0,1398.0,261.0,823.0,263.0,5.0641,234900.0
2645,-118.3,33.98,48.0,1998.0,410.0,1176.0,382.0,3.0455,102400.0
2791,-118.3,34.06,47.0,1390.0,872.0,2860.0,827.0,1.4680,137500.0
2857,-118.3,33.73,47.0,2852.0,603.0,1130.0,560.0,4.1940,293900.0
2878,-118.3,34.00,40.0,1131.0,281.0,859.0,230.0,1.1806,134600.0

In [ ]:
california_housing.loc[california_housing.housing_median_age.isin([27,39])]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
14,-117.97,33.73,27.0,2097.0,325.0,1217.0,331.0,5.7121,222500.0
52,-122.21,37.80,39.0,2003.0,500.0,1109.0,464.0,3.0682,156500.0
54,-117.90,34.09,39.0,1726.0,333.0,892.0,335.0,4.3409,191800.0
...,...,...,...,...,...,...,...,...,...
2893,-118.27,34.11,39.0,3825.0,916.0,1378.0,746.0,4.4094,352600.0
2909,-122.11,37.41,27.0,5110.0,1599.0,2764.0,1482.0,3.4198,351900.0
2945,-122.48,37.65,39.0,3348.0,666.0,1817.0,668.0,4.2593,227400.0
2957,-118.23,33.91,27.0,1694.0,393.0,1890.0,373.0,3.0341,89100.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0

In [ ]:
california_housing['owner'] = 'Shashwat'

In [ ]:
california_housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,owner
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,Shashwat
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,Shashwat
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,Shashwat
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,Shashwat
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,Shashwat

In [ ]:
california_housing.loc[:,['latitude']]

      latitude
0        37.37
1        34.26
2        33.78
3        33.82
4        36.33
...        ...
2995     34.42
2996     34.06
2997     36.30
2998     34.10
2999     34.42

[3000 rows x 1 columns]

#Tutorial-3

In [26]:
reviews = pd.read_csv('/content/drive/MyDrive/Practice_datasets/winemag-data-130k-v2.csv')
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [27]:
reviews.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [28]:
reviews.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

In [29]:
reviews.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams',
       'Christina Pickard'], dtype=object)

In [30]:
reviews.taster_name.value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

In [31]:
review_points_meaan = reviews.points.mean()
reviews.points.map(lambda p: p - review_points_meaan)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [32]:
def remean_points(row):
  row.points = row.points - review_points_meaan
  return row

reviews.apply(remean_points, axis='columns')

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,1.552862,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,129967,US,Citation is given as much as a decade of bottl...,NaN,1.552862,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,129968,France,Well-drained gravel soil gives this wine its c...,Kritt,1.552862,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [33]:
reviews.points - review_points_meaan

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [34]:
def star_review(row):
    if(row.country == 'Canada'):
        row['star_review'] = 3
    elif(row.points>=95):
        row['star_review'] = 3
    elif(row.points>=85):
        row['star_review'] = 2
    else:
        row['star_review'] = 1
    return row

star_ratings = reviews.apply(star_review, axis='columns').star_review

#Tutorial-4

In [41]:
reviews.groupby('points').points.max()

points
80      80
81      81
82      82
83      83
84      84
85      85
86      86
87      87
88      88
89      89
90      90
91      91
92      92
93      93
94      94
95      95
96      96
97      97
98      98
99      99
100    100
Name: points, dtype: int64

In [36]:
reviews.head().iloc[0]

Unnamed: 0                                                               0
country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [38]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

/tmp/ipython-input-38-506966275.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

In [43]:
reviews.groupby('winery').points.mean()

winery
1+1=3                  86.666667
10 Knots               83.250000
100 Percent Wine       86.333333
1000 Stories           90.500000
1070 Green             88.000000
                         ...
Órale                  91.000000
Öko                    85.000000
Ökonomierat Rebholz    91.500000
àMaurice               90.550000
Štoka                  89.333333
Name: points, Length: 16757, dtype: float64

In [45]:
reviews.groupby(['country','province']).apply(lambda df: df.loc[df.points.idxmax()])

/tmp/ipython-input-45-4223394852.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reviews.groupby(['country','province']).apply(lambda df: df.loc[df.points.idxmax()])

                            Unnamed: 0    country  \
country   province
Argentina Mendoza Province       82754  Argentina
          Other                  78303  Argentina
Armenia   Armenia                66146    Armenia
Australia Australia Other        37882  Australia
          New South Wales        85337  Australia
...                                ...        ...
Uruguay   Juanico                 9133    Uruguay
          Montevideo             15750    Uruguay
          Progreso               93103    Uruguay
          San Jose               39898    Uruguay
          Uruguay                39361    Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 14 columns]